### ISSUE TITLE
Invitation to join force with walkable project

### ISSUE THREAD

**Issue by myguidingstar** [TheLadders/sqlium#6]
Hi all,
I'm happy to discover sqlium. The readme really excited me. However I can't find much documentation about sqlium's features and approach.
I've been working on a similar project called walkable which imo shares the goal with sqlium.
https://github.com/walkable-server/walkable/
Of course Walkable is far from perfect. That's why I'm looking forward to some collaboration between two projects.
Best regards.

**Comment by mgaare** [comment]
Hello!

Thanks for your interest! I recently added some more to the sqlium readme to describe its DSL. Still looking to add api documentation and some usage examples. 

There are a few goals that influenced sqlium's design that might be a little different from walkable. Its main original use case was reading a lot of entities at a time, so it's written to do that quite efficiently. It doesn't support filtering and can't properly be considered a query generator or ORM replacement. 

I'll post in here again when I do the next round of documentation updates. 

Cheers

**Comment by mgaare** [comment]
There have been some more updates to the readme, including usage documentation, at the project's new home:

https://github.com/purefnorg/sqlium

**Comment by myguidingstar** [comment]
It's clearer now. I will try sqlium soon. Thanks
